[icons]  
name = "awesome5"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#81a1c1"
idle_fg = "#4c566a"
info_bg = "#7995a1"
info_fg = "#4c566a"
good_bg = "#a3be8c"
good_fg = "#4c566a"
warning_bg = "#ebcb8b"
warning_fg = "#4c566a"
critical_bg = "#bf616a"
critical_fg = "#4c566a"

[[block]]
block = "watson"
show_time = true
state_path = "/home/michael/.config/watson/state"

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "net"
device = "wlan0"
ssid = true
interval = 5

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "memory"
format_mem = "{Mup}%"
interval = 5

[[block]]
block = "sound"
format = "♫ {volume}"

[[block]]
block = "time"
interval = 60
format = "%a %d-%m | %R"

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"


[[block]]
block = "battery"
interval = 10
format = "{percentage}%"
