theme = "kanagawa"

[editor]
line-number = "relative"
bufferline = "multiple"
auto-pairs = false
cursorline = true
true-color = true
color-modes = true
rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.whitespace]
render = "all"
