[icons]  
icons = "material-nf"

[theme]
theme= "nord-dark"

[theme.overrides]
idle_bg = "#363646"
idle_fg = "#C8C093"

info_bg =  "#76946A"
info_fg =  "#C8C093"

warning_bg = "#2D4F67"
warning_fg = "#E46876"

critical_bg = "#2D4F67"
critical_fg = "#FF5D62"

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "net"
device = "wlan0"
interval = 5

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "memory"
format = "$icon $mem_total_used_percents.eng(w:2)"
interval = 5

[[block]]
block = "sound"
driver= "pulseaudio"
format = "$icon {$volume.eng(w:2) |}"

[[block]]
block = "time"
interval = 60

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
format = "$icon $percentage {$time |}"
