[icons]  
name = "awesome5"

[theme]
name = "space-villain"
[theme.overrides]
idle_bg = "#3b4252"
info_bg = "#3b4252"
good_bg = "#3b4252"
warning_bg = "#3b4252"
critical_bg = "#3b4252"

[[block]]
block = "watson"
show_time = true
state_path = "/home/michael/.config/watson/state"

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "net"
device = "wlan0"
interval = 5

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "memory"
format_mem = "{mem_used_percents}%"
interval = 5

[[block]]
block = "sound"
format = "♫ {volume}"

[[block]]
block = "time"
interval = 60
format = "%a %d-%m | %R"

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"


[[block]]
block = "battery"
interval = 10
format = "{percentage}%"
