# {{{ Zplugin
### Added by Zplugin's installer
source '/home/michael/.zplugin/bin/zplugin.zsh'
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin's installer chunk

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

zplugin ice pick"async.zsh" src"pure.zsh"; zplugin light sindresorhus/pure

source ~/.dotfiles/zsh/pure-prompt/async.zsh
source ~/.dotfiles/zsh/pure-prompt/pure.zsh

zplugin light urbainvaes/fzf-marks

zplugin light zsh-users/zsh-autosuggestions
zplugin light zsh-users/zsh-syntax-highlighting

export NVM_LAZY_LOAD=true
zplugin light lukechilds/zsh-nvm

# }}}
#
setopt RM_STAR_WAIT
export SAVEHIST=32768;
export HISTSIZE=32768;
export HISTFILESIZE=$HISTSIZE;
export HISTFILE=/home/michael/.zsh_history;
export HISTCONTROL=ignoredups;
export HISTORY_IGNORE="(ls|cd|pwd|exit|date)";

#source ~/.dotfiles/zsh/zsh-syntax-highlighting
source ~/.dotfiles/zsh/aliases.zsh
#source ~/.dotfiles/zsh/completion.zsh

# {{{ Python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$HOME/.local/bin:$PATH"
eval "$(pyenv init -)"

export VIRTUALENVWRAPPER_SCRIPT=/home/michael/.pyenv/versions/3.6.0/bin/virtualenvwrapper.sh
[ -s "/home/michael/.pyenv/versions/3.6.0/bin/virtualenvwrapper_lazy.sh" ] && source "/home/michael/.pyenv/versions/3.6.0/bin/virtualenvwrapper_lazy.sh"
# }}}

export PATH="$PATH:$HOME/.rvm/bin:$HOME/local/go/bin"

# {{{ Exercism
if [ -f ~/.config/exercism/exercism_completion.zsh ]; then
  source ~/.config/exercism/exercism_completion.zsh
fi
# }}}
